org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

#fabric Properties
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.1
fabric_version=0.138.3+1.21.10
loom_version=1.13-SNAPSHOT
parchment_version=1.21.10:2025.10.12

#compat
scalablelux_compat=0.1.6+fabric.c25518a
moonrise_compat=0.8.0-beta.4+c0e63e9

#mod properties
version=r2.0.1
maven_group=dev.ianaduarte
archives_base_name=mydriasis
